services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_PASSWORD=library_secret
      - MAIL_USERNAME=your_email@gmail.com
      - MAIL_PASSWORD=your_app_password
    depends_on:
      - db
    networks:
      - library-net

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=library_secret
      - MYSQL_DATABASE=library_db
    volumes:
      - db_data:/var/lib/mysql
      # - ./test-data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library-net

networks:
  library-net:

volumes:
  db_data:
